# Generated by Django 5.0.1 on 2024-05-03 00:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_video_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='username',
            name='product',
        ),
    ]
